#!/usr/bin/python3
"""
Band Scanner

Scans up to three selected bands for signals.

UI source file: bandScanner.ui
"""
import tkinter as tk
from time import sleep
import tkinter.ttk as ttk
from multiprocessing.process import parent_process

from barPlotter import barPlotter
from tkinter import messagebox
from graphObject import graphObject

import bandScannerui as baseui

import globalvars as gv


#
# Manual user code
#


class bandScanner(baseui.bandScannerUI):


    def __init__(self,  master=None, mainWindow=None, **kw):
        self.master = master                            # pointer to the root master.Needed for scheduling "after" events
        self.mainWindow = mainWindow

        self.startingFrequency = None                   # tracks the frequency of the radio upon entry to the scan window
                                                        # This allows the cancel button to reset the frequency upon close

        self.frequencyScrolling = False                 # tracks when the scrollbar is being used to adjust frequency
                                                        # turns on when button 1 pressed, off when released

        #
        #   DEFAULTS
        #


        self.MaxADCCount = 120  # Maximum number of times that the ADC can be read.
                                # CEC hardwires 120 here
        self.Bandwidth = 2000
        self.repeatCount = 3    # Scan each band 3x

        self.FREQ_Y_MAX = 70  # maximum value of Y values

        self.numberBandsChecked = 0     # Total number of bands checked

        self.targetGraph = [None]  * 3
        self.scanlist = []              # used to identify which targetGraphs are activated and require band scans
        self.scanlistIndex = None       # the index into scanlist that is currently being processed (0-2)
        self.processDataCount = None    # real time count of the number of data buffers left to process


        self.averageBuffer = bytearray(self.MaxADCCount)    # Tracks the current average of a frequency



        self.spectrumScanning = False               # default to scanning off

        self.windowResized = False                  # these two variables are used to handle resizing of screen
        self.windowResizedObj = None                # while window is active. When the resized is detected,
                                                    # the windowResized flag is set to true and a future
                                                    # event is created to eventually update the window after 100ms
                                                    # Each time the reseize event is called, the current future event
                                                    # is deleted and a new one is scheduled. Only after 100 ms of no
                                                    # new resize, is the scheduled event finally executed, the graph is
                                                    # updated and the flag is set back to False.

        self.initUXComplete = False                 # used to avoid errors generated by incoming data prior to completion
        #                                             # of initialization of object

        super().__init__(self.master, **kw)


        #
        #   Make sure that a close by the Window manager goes to the same close callback
        #
        self.protocol("WM_DELETE_WINDOW", self.close_CB)

        self.initUX()           # This deals with any initiation that needs to be done after the Object is fully
                                # instantiated.

    def initUX(self):
        # self.title("Frequency Spectrum")
        # self.geometry("825x675")
        self.geometry(gv.POPUP_WINDOW_OFFSET)

        self.wait_visibility()  # required on Linux
        self.grab_set()
        self.transient(self.master)



        self.frequencyTuning_VAR.set(0)                                                # Set scrollbar to middle


        self.startingFrequency = self.mainWindow.theVFO_Object.getIntPrimaryVFO()
        #
        #   Set the defaults for scanning
        #
        #   repeatCount = 3   - scan 3 times reporting the average
        #   self.MaxADCCount = 120  constant, always get back 120 slots
        #   100 - this is the bandwidth  100 x 20 = 2000
        #
        self.mainWindow.theRadio.updateFrequencySpectrumOptions(self.repeatCount, 0, self.MaxADCCount, 100)
        #
        #   Instantiate the 3 objects to do the plotting
        #
        self.targetGraph[0] = graphObject(self.band0, self.updateBandFrequency_CB, self.resizeCanvas_CB, self.frequencyTuning_VAR)
        self.targetGraph[1] = graphObject(self.band1, self.updateBandFrequency_CB, self.resizeCanvas_CB, self.frequencyTuning_VAR)
        self.targetGraph[2] = graphObject(self.band2, self.updateBandFrequency_CB, self.resizeCanvas_CB, self.frequencyTuning_VAR)


        self.initUXComplete = True


    #
    #   resizeCanvas_CB and refreshCanvas work together to deal with any resizing of the canvas.
    #   When a resize is detected, resizeCanvas_CB is called and it schedules a future execution of
    #   refreshCanvas.  But resizing generates a lot of callbacks... So if the resize process is underway
    #   each new event cancels the prior "after refreshCanvas" and creates a new one 100ms in the future
    #   Eventually the events end, and the last refreshCanvas future event runs and replots the data
    #
    def resizeCanvas_CB(self, event=None):
        if self.windowResized:
            self.master.after_cancel(self.windowResizedObj)
        else:
            self.windowResized = True
        self.windowResizedObj = self.master.after(gv.config.get_MCU_Update_Period(), self.refreshCanvas)

        #
        #   Refreshes the canvas if the window has been resized.
        #

    def refreshCanvas(self):
        if self.initUXComplete:
            #
            #   Update canvas size
            #
            for i in range(len(self.targetGraph)):
                if self.targetGraph[i].activated():
                    self.targetGraph[i].refreshCanvas()
                    self.setFrequency(i)

    #
    #   Calculates frequency for a particular band. The parameter "i" is the band index
    #   in self.targetGraph
    #
    def setFrequency(self, i):
        f = gv.formatVFO(str(self.targetGraph[i].getFrequency(int(self.frequencyTuning_VAR.get()))))
        getattr(self, "band" + str(i) + "Frequency_VAR").set(str(f))
        self.targetGraph[i].drawHighLightBars()

    def getFrequency(self, i):
        f = gv.unformatFrequency(getattr(self, "band" + i + "Frequency_VAR").get())
        return int(f)



    def updateBandFrequency_CB(self, theBand):
        for i in range(len(self.targetGraph)):
            if self.targetGraph[i] == theBand:
                self.setFrequency(i)



    def frequencyTuning_CB(self, scale_value):
        for i in range(len(self.targetGraph)):
            if self.targetGraph[i].activated():
                self.targetGraph[i].clearCanvas("tuningLine")
                self.setFrequency(i)


    def bandGo_CB(self, widget_id):
        f=self.getFrequency(widget_id.replace("band","").replace("GO_Button",""))
        self.mainWindow.theRadio.Set_New_Frequency(f)


    #
    #   Does the work of allocating a Free graphObject
    #
    def allocateGraphObj(self, bandID, bandStart, bandEnd, maxY=70, scrollbarSize=120):
        for i in range(len(self.targetGraph)):
            if self.targetGraph[i].available():
                self.targetGraph[i].activate(bandID, bandStart, bandEnd, self.Bandwidth, self.FREQ_Y_MAX, scrollbarSize)
                self.setFrequency(i)
                self.scanlist.append(i)     # add i to list of scannable bands
                return True

        #
        #   If it falls thru, no available slots. Display warning message
        #

        messagebox.showwarning(title="No Available Graph Areas",
            message="Attempt to allocate more than 3 bands for scanning", parent=self,
            detail="You must first free up a band and then try again.")
        return False

    #
    #   This is used to release a graphObject when the checkbox for a band
    #   is unchecked. If it finds a match, it releases it. No match? just returns
    #   instead of generating an error
    #
    def releaseGraphObj(self, bandID):
        for i in range(len(self.targetGraph)):
            if self.targetGraph[i].get_bandID() == bandID:
                self.targetGraph[i].clearCanvas("All")
                self.targetGraph[i].deactivate()
                getattr(self, "band" + str(i) + "Frequency_VAR").set("")
                # print("before removal scanlist=", self.scanlist)
                self.scanlist.remove(i)         # remove this band from scanable channels
                # print("after removal scanlist=", self.scanlist)
                return True
        #
        #   If it dropped thru, tried to deactivate a bandID that was not found.
        #
        return False

    #
    #   This callback happens when a user clicks one of the bands listed in the bandScanner
    #   window. Since each of the bands, for example 160M, is named "Band160m", can use that to
    #   have a single routine that handles all the checkboxes
    #

    def band_Checked_CB(self, widget_id):
        # print("band checked callback, widget_id=", widget_id)

        if getattr(self,widget_id+"_Checked_VAR").get() == '1':
            #
            #   Trying to allocate this band. Allocate it. If True, success
            #
            if self.allocateGraphObj(widget_id,gv.bandStart[widget_id], gv.bandEnd[widget_id],
                                     self.FREQ_Y_MAX, self.MaxADCCount):
                #
                #   True indicates successful allocation. Enable Scan button and return
                #
                self.scan_Button.configure(state="normal")
                return
            else:
                #
                #   False indicates no available slots. Error message already generated to free up slots
                #
                getattr(self,widget_id+"_Checked_VAR").set('0')
                return
        else:
            #
            #   Trying to deactivate a graphobject
            #
            if self.releaseGraphObj(widget_id):
                if len(self.scanlist) == 0:   #  if there is no active bands, disable scan button
                    self.scan_Button.configure(state="disabled")
                return
            else:
                print("trying to release a band that is not allocated, band=", widget_id)
                return

    # def processData(self,buffer):
    #     self.processDataCount += 1
    #
    #     if self.processDataCount == self.repeatCount:
    #         self.displayData()
    def updateAverage(self,buffer, valueCount):
        byteBuffer =bytearray.fromhex(buffer)

        for x, y in enumerate(byteBuffer):
            # if y >5:
            #     print("larger value", x, y)
            # if x == 12:
            #     print("newvalue =", y)

            tmp = int(round(self.averageBuffer[x] +((y-self.averageBuffer[x])/valueCount)))

            if tmp > 255:
                print("tmp too big, tmp")
            self.averageBuffer[x] = tmp

    def process_Spectrum_Data(self,buffer):
        if self.spectrumScanning:
            # print("processing spectrum buffer#",self.processDataCount,buffer)
            self.processDataCount += 1
            #
            #   Average the data provided by the buffer
            #
            self.updateAverage(buffer, self.processDataCount)
            # print("average buffer ", self.averageBuffer)
            #
            #   Check whether we have received all the buffers we were supposed to get
            #
            if self.processDataCount == self.repeatCount:
                #
                #   Display data for the band we just completed
                #
                # print("band processing complete")
                # print(self.averageBuffer)
                self.setFrequency(self.scanlist[self.scanlistIndex])

                self.targetGraph[self.scanlist[self.scanlistIndex]].displayData(self.averageBuffer)
                # self.targetGraph[self.scanlistIndex].process_Data(self.averageBuffer)

                self.scanlistIndex += 1
                if self.scanlistIndex < len(self.scanlist):
                    self.sendNextScanRequest(self.scanlist[self.scanlistIndex])
                else:
                    #
                    #   We have finished processing the scanlist and can go back to normal operation
                    #
                    self.spectrumScanning = False
                    self.parameterStatus("normal")



    def sendNextScanRequest(self,i):
        self.processDataCount = 0
        self.averageBuffer = bytearray(self.MaxADCCount)        # Reinitialized average buffer to all zeros

        self.mainWindow.theRadio.startFrequencySpectrumScan(self.targetGraph[i].getStartScanF(),
                                                           self.repeatCount)

    #
    #   This is called when the Scan button is pressed. It creates a list of bands to scan and then
    #   scans the first one. Once the scan is processed on the first band, the next band is kicked off
    #   in the process_Spectrum_Data method. This controls the speed of instructions to the MCU
    #   and avoids overwhelming it.
    #
    def scan_CB(self):
        self.spectrumScanning = True
        self.parameterStatus("disabled")

        #
        #   Find all the graphObjects that are activated
        #
        if len(self.scanlist) != 0:
            for i in range(len(self.scanlist)):
                self.targetGraph[self.scanlist[i]].clearCanvas()
            self.scanlistIndex = 0
            self.sendNextScanRequest(self.scanlistIndex)



    def parameterStatus(self, status):
        #
        #   Convenience routine to turn all the buttons on or off. When Start button is called, all these
        #   buttons are "disabled". When the scan is done, they are re-enabled.
        #

        self.band0GO_Button.configure(state=status)
        self.band1GO_Button.configure(state=status)
        self.band2GO_Button.configure(state=status)


        self.scan_Button.configure(state=status)
        self.close_Button.configure(state=status)
        self.cancel_Button.configure(state=status)

        self.Band160m.configure(state=status)
        self.Band80m.configure(state=status)
        self.Band40m.configure(state=status)
        self.Band30m.configure(state=status)
        self.Band20m.configure(state=status)
        self.Band17m.configure(state=status)
        self.Band15m.configure(state=status)
        self.Band12m.configure(state=status)
        self.Band10m.configure(state=status)

        self.frequencyTuning_Scale.configure(state=status)

        if self.spectrumScanning:
            self.scan_Button_VAR.set("Running")
        else:
            self.scan_Button_VAR.set("Scan")


    def close_CB(self, widget_id="cancel_Button"):
        #
        #   Needs to invoke a mainWindow routine instead of directly calling these attributes
        #
        self.mainWindow.frequencySpectrumMode = "FreqScan"
        self.mainWindow.consumerDSPdata = self.mainWindow
        self.mainWindow.highlightCWorSpectrumBoxes(True)
        self.mainWindow.theRadio.Set_Spectrum_Mode(95)
        if widget_id == "cancel_Button":
            self.mainWindow.theRadio.Set_New_Frequency(self.startingFrequency)
            # print("reseting frequency=", self.startingFrequency)
        self.mainWindow.consumerSpectrumdata = None
        self.destroy()


if __name__ == "__main__":
    root = tk.Tk()
    widget = bandScanner(root)
    root.mainloop()
