#!/bin/zsh

mkdir cecNext_Linux
cp cecNext cecNext_Linux
cp Install_cecNext_Linux cecNext_Linux
cp Uninstall_cecNext_Linux cecNext_Linux
cp ../../../../dist/cec_nextion_emulator-0.1.0-py3-none-any.whl cecNext_Linux
#cp ../../defaultCECNextionEmulator.py cecNext_Linux/defaultCECNextionEmulator.ini

COPYFILE_DISABLE=true tar -czv --no-xattrs -f cecNext_Linux.tar.gz --exclude=".DS_Store" cecNext_Linux
rm -r cecNext_Linux