#!/usr/bin/python3
"""
Band Scanner

Scans up to three selected bands for signals.

UI source file: bandScanner.ui
"""
import tkinter as tk
import tkinter.ttk as ttk

from barPlotter import barPlotter

import bandScannerui as baseui


#
# Manual user code
#

class bandScanner(baseui.bandScannerUI):
    #
    #   graphObject is an inner class that is used as a convenience to manage the 3 canvases that can display a
    #   band scan. Being an inner class, it is isolated from the outer class instance variables. Consequently,
    #   all communication is via class get/set/query methods
    #
    class graphObject:
        def __init__(self, mycanvas=None, **kw):
            print("I am an inner class")
            self.plotterAvg = barPlotter(self, mycanvas, 120, 70)
    def __init__(self,  master=None, mainWindow=None, **kw):
        self.master = master                            # pointer to the root master.Needed for scheduling "after" events
        self.mainWindow = mainWindow

        self.lastFrequency = None                 # tracks the last center frequency in case it has been changed
                                                        # between scans

        self.frequencyScrolling = False                 # tracks when the scrollbar is being used to adjust frequency
                                                        # turns on when button 1 pressed, off when released

        #
        #   DEFAULTS
        #


        self.MaxADCCount = 120  # Maximum number of times that the ADC can be read.
                                # CEC hardwires 120 here
        self.repeatCount = 3    # Scan each band 3x

        self.FREQ_Y_MAX = 70  # maximum value of Y values

        self.numberBandsChecked = 0     # Total number of bands checked


        self.averageBuffer = bytearray(self.MaxADCCount)    # Tracks the current average of a frequency



        self.spectrumScanning = False               # default to scanning off

        self.windowResized = False                  # these two variables are used to handle resizing of screen
        self.windowResizedObj = None                # while window is active. When the resized is detected,
                                                    # the windowResized flag is set to true and a future
                                                    # event is created to eventually update the window after 100ms
                                                    # Each time the reseize event is called, the current future event
                                                    # is deleted and a new one is scheduled. Only after 100 ms of no
                                                    # new resize, is the scheduled event finally executed, the graph is
                                                    # updated and the flag is set back to False.

        # self.initUXComplete = False                 # used to avoid errors generated by incoming data prior to completion
        #                                             # of initialization of object

        super().__init__(self.master, **kw)


        #
        #   Make sure that a close by the Window manager goes to the same close callback
        #
        self.protocol("WM_DELETE_WINDOW", self.close_CB)

        self.initUX()           # This deals with any initiation that needs to be done after the Object is fully
                                # instantiated.

    def initUX(self):
        # self.title("Frequency Spectrum")
        self.geometry("800x625")

        self.wait_visibility()  # required on Linux
        self.grab_set()
        self.transient(self.master)



        self.frequencyTuning_VAR.set(60)                                                # Set scrollbar to middle
        #
        #   Create two plotter objects. Top one is for average signal strength. Bottom is for Peak signal strength
        #
        # self.plotterAvg = barPlotter(self, self.frequencyPlotCanvas, self.MaxADCCount, self.FREQ_Y_MAX)
        # self.plotterPeak = barPlotter(self, self.waterfall_Canvas, self.MaxADCCount, self.FREQ_Y_MAX, barColor="green")
        #
        # self.remainingCount_VAR.set(self.repeat_VAR.get())              # Set remaining count to current count
        # self.updateScanParameters()                                     # Can now format Frequency graphs

        self.lastFrequency = self.mainWindow.theVFO_Object.getIntPrimaryVFO()
        #
        #   Set the defaults for scanning
        #
        #   repeatCount = 3   - scan 3 times reporting the average
        #   self.MaxADCCount = 120  constant, always get back 120 slots
        #   100 - this is the bandwidth  100 x 20 = 2000
        #
        self.mainWindow.theRadio.updateFrequencySpectrumOptions(self.repeatCount, 0, self.MaxADCCount, 100)

        self.testClass = self.graphObject(self.band1Plot_Canvas)
        self.testClass1 = self.graphObject(self.band2Plot_Canvas)

        self.initUXComplete = True


    def resizeCanvas_CB(self, event=None):
        pass

    def frequencyTuning_CB(self, scale_value):
        pass

    def frequencyTuningPress_CB(self, event=None):
        pass

    def frequencyTuningRelease_CB(self, event=None):
        pass

    def bandGo_CB(self, widget_id):
        print("bandGo_CB: widget_id=", widget_id)

    def band_Checked_CB(self, widget_id):
        print("band checked callback, widget_id=", widget_id)

        match widget_id:
            case "band160m_checkbox":
                if self.band160m_Checked_VAR.get() == '1':
                    print("160m turned on")
                else:
                    print("160m turned off")
            case "band80m_checkbox":
                pass
            case "band40m_checkbox":
                pass
            case "band30m_checkbox":
                pass
            case "band20m_checkbox":
                pass
            case "band17m_checkbox":
                pass
            case "band12m_checkbox":
                pass
            case "band10m_checkbox":
                pass
            case _:
                print("unknown band", widget_id)


    def scan_CB(self):
        print("scan_CB")


    def close_CB(self):
        #
        #   Needs to invoke a mainWindow routine instead of directly calling these attributes
        #
        self.mainWindow.frequencySpectrumMode = "FreqScan"
        self.mainWindow.consumerDSPdata = self.mainWindow
        self.mainWindow.highlightCWorSpectrumBoxes(True)
        self.mainWindow.theRadio.Set_Spectrum_Mode(95)
        self.mainWindow.theRadio.Set_New_Frequency(self.lastFrequency)
        print("reseting frequency=", self.lastFrequency)
        self.destroy()


if __name__ == "__main__":
    root = tk.Tk()
    widget = bandScanner(root)
    root.mainloop()
