#!/usr/bin/python3
"""
Frequency Spectrum

Displays an area of the Frequency showing signal strength

UI source file: frequencySpectrum.ui
"""

import frequencySpectrumui as baseui

from barPlotter import barPlotter
import globalvars as gv



#
# Manual user code
#

class frequencySpectrum(baseui.frequencySpectrumUI):
    def __init__(self,  master=None, mainWindow=None, centerFrequency=None, **kw):
        self.master = master                            # pointer to the root master.Needed for scheduling "after" events
        self.mainWindow = mainWindow
        self.centerFrequency = centerFrequency          # the current (VFO) frequency is passed and saved
        self.originalFrequency = centerFrequency        # Save frequency at entry so can restore if cancel

        self.startFrequency = None                      # starting frequency for scanning
        self.stopFrequency = None                       # stopping frequency for scanning
        self.bandwidth = None                           # the width of the band being scanned
        self.stepSize = None                            # size of steps (frequency samples)
        self.lastCenterFrequency = None                 # tracks the last center frequency in case it has been changed
                                                        # between scans

        self.frequencyScrolling = False                 # tracks when the scrollbar is being used to adjust frequency
                                                        # turns on when button 1 pressed, off when released

        #
        #   DEFAULTS
        #

        self.lastCenterFrequency = self.centerFrequency     # save current frequency, need this to check if current
                                                            # frequency has been changed

        self.MaxADCCount = 120  # Maximum number of times that the ADC can be read.
                                # CEC hardwires 120 here

        self.FREQ_Y_MAX = 70  # maximum value of Y values

        self.peakBuffer = bytearray(self.MaxADCCount)       # Tracks the peak value of a frequency
        self.averageBuffer = bytearray(self.MaxADCCount)    # Tracks the current average of a frequency

        self.bandwidthValues = {"60k":"60,000","120k":"120,000","240k":"240,000","360k":"360,000", "480k":"480,000"}



        self.spectrumScanning = False               # default to scanning off

        self.windowResized = False                  # these two variables are used to handle resizing of screen
        self.windowResizedObj = None                # while window is active. When the resized is detected,
                                                    # the windowResized flag is set to true and a future
                                                    # event is created to eventually update the window after 100ms
                                                    # Each time the reseize event is called, the current future event
                                                    # is deleted and a new one is scheduled. Only after 100 ms of no
                                                    # new resize, is the scheduled event finally executed, the graph is
                                                    # updated and the flag is set back to False.
        self.frequencyChangeCheckPtr = None         # used to track the routine id that checks for frequency changes from the knob
                                                    # since it is a future event, must be cancelled on all exists of this object

        self.initUXComplete = False                 # used to avoid errors generated by incoming data prior to completion
                                                    # of initialization of object

        super().__init__(self.master, **kw)


        #
        #   Make sure that a close by the Window manager goes to the same close callback
        #
        self.protocol("WM_DELETE_WINDOW", self.cancel_CB)

        self.initUX()           # This deals with any initiation that needs to be done after the Object is fully
                                # instantiated.

    def initUX(self):
        # self.title("Frequency Spectrum")
        self.geometry(gv.POPUP_WINDOW_OFFSET)

        self.wait_visibility()  # required on Linux
        self.grab_set()
        self.transient(self.master)

        self.repeat_VAR.set('10')                       # defaults to run the scan 10 times

        # Update bandwidth to use selected delimiter
        for key, value in self.bandwidthValues.items():
            self.bandwidthValues[key] = value.replace(',', gv.NUMBER_DELIMITER)
            self.bandwidth_Menu.entryconfigure(value, label=self.bandwidthValues[key])

        self.bandwidthSelected_VAR.set(self.bandwidthValues['240k'])

        self.frequencyTuning_VAR.set(60)                                                # Set scrollbar to middle
        self.currentFrequency_VAR.set(gv.formatVFO(str((self.lastCenterFrequency)) ) )  # Set frequency
        #
        #   Create two plotter objects. Top one is for average signal strength. Bottom is for Peak signal strength
        #
        self.plotterAvg = barPlotter(self, self.frequencyPlotCanvas, self.MaxADCCount, self.FREQ_Y_MAX)
        self.plotterPeak = barPlotter(self, self.waterfall_Canvas, self.MaxADCCount, self.FREQ_Y_MAX, barColor="red")

        self.remainingCount_VAR.set(self.repeat_VAR.get())              # Set remaining count to current count
        self.updateScanParameters()                                     # Can now format Frequency graphs

        self.checkForFrequencyChange()              # kick off process that will check on frequency change by knob

        self.initUXComplete = True
    #
    #   This resets these two bytearrays that track average and peak to zero. Used when starting a new scan
    #

    def reinitializeValues(self):
        self.peakBuffer = bytearray(self.MaxADCCount)
        self.averageBuffer = bytearray(self.MaxADCCount)

    #
    #   When things change, this routine is called to reset all parameters
    #
    def updateScanParameters(self):
        #
        #   convenience routine to make sure start and end are multiples of 120
        #
        # def roundToNearest(n, base):
        #     return base * round(n / base)
        #
        #   When the bandwidth is changed, this routine is called to re-establish the scanning
        #
        # print(self.bandwidthSelected_VAR.get(),self.bandwidthSelected_VAR.get().replace(",","").replace(".",""))
        self.bandwidth = int(self.bandwidthSelected_VAR.get().replace(",","").replace(".",""))
        self.calculatedSampleSize_VAR.set(int(self.bandwidth / self.MaxADCCount) )

        self.startFrequency=gv.roundToNearest((self.centerFrequency - self.bandwidth/2),int(self.calculatedSampleSize_VAR.get()))
        self.startFrequency_VAR.set(gv.formatVFO(str(self.startFrequency)))

        self.stopFrequency = gv.roundToNearest((self.centerFrequency - int(self.calculatedSampleSize_VAR.get()) + self.bandwidth/2),int(self.calculatedSampleSize_VAR.get()))
        self.stopFrequency_VAR.set(gv.formatVFO(str(self.stopFrequency)))

        self.mainWindow.theRadio.updateFrequencySpectrumOptions(int(self.repeat_VAR.get()), 0, self.MaxADCCount, round(int(self.calculatedSampleSize_VAR.get())/20))

        # print("finished updating scan parameters", round(int(self.calculatedSampleSize_VAR.get())/20))


    def updatePeak(self,buffer):
        byteBuffer =bytearray.fromhex(buffer)
        for x, y in enumerate(byteBuffer):
            if y > self.peakBuffer[x]:
                self.peakBuffer[x] = y


    def updateAverage(self,buffer):
        byteBuffer =bytearray.fromhex(buffer)
        valueCount = 1+int(self.repeat_VAR.get()) - int(self.remainingCount_VAR.get())

        for x, y in enumerate(byteBuffer):

            tmp = int(round(self.averageBuffer[x] +((y-self.averageBuffer[x])/valueCount)))

            if tmp > 255:
                print("tmp too big, tmp")
            self.averageBuffer[x] = tmp


    def process_Spectrum_Data(self, buffer):
        #
        # This plots the frequency ADC values. Uses generic routines to figure out sizes of canvas and bar sizes
        #

        self.updateAverage(buffer)          # Process buffer to update the Average of each bar

        self.updatePeak(buffer)             # Process buffer to look for a higher peak


        self.remainingCount_VAR.set(str(int(self.remainingCount_VAR.get()) - 1))        # reduce the count remaining


        if int(self.remainingCount_VAR.get())==0:               #   if zero remaining, then we can plot average and peak

            self.plotterPeak.process_Data(self.peakBuffer)
            self.plotterAvg.process_Data(self.averageBuffer)

            self.updateTuningLine()
            self.scanningComplete()

    def calculateBarPosition(self):
        #
        #   Returns the bar position. Routine exists if for some future
        #   reason there was a need to map a frequency onto a scroll bar that
        #   was not dividable by 120
        #
        return(int(self.frequencyTuning_VAR.get()))



    def updateTuningLine(self):
        #
        #   Updates the location of the tuning bars
        #
        barPos = self.calculateBarPosition()
        self.plotterAvg.drawHighLightBars(barPos)
        self.plotterPeak.drawHighLightBars(barPos)



    def updateCurrentFrequency(self):
        #
        #   updates the current frequency of the tuning bar as displayed in the middle below the scroll bar
        #
        barPos = self.calculateBarPosition()

        self.centerFrequency =  self.startFrequency + (int(self.calculatedSampleSize_VAR.get())*barPos)

        self.currentFrequency_VAR.set(gv.formatVFO(str(self.centerFrequency)))
    #
    #   This called when value changes on scale
    #   TODO needs to avoid mutiple executiong of updateCurrentFrequency and updateTuningLine - probably a performance
    #   issue
    #
    def frequencyTuning_CB(self,event=None):
        #
        #   called when the tuning scroll bar is moved
        #
        self.updateCurrentFrequency()
        self.updateTuningLine()
    #
    #   Sets the new frequency for the radio when mouse button released.
    #   Resets frequencyScrolling flags so that other routines can mess with the frequency again
    #
    def frequencyTuningRelease_CB(self, event=None):
        self.mainWindow.theRadio.Set_New_Frequency(self.centerFrequency)
        self.frequencyScrolling = False
#
    #
    #   Callback when mouse 1 button is pressed. sets the frequencyScrolling
    #   Flag to signal others not to mess with frequency related items for now
    #
    def frequencyTuningPress_CB(self, event=None):
        self.frequencyScrolling = True

    #
    #   Callback when the # of repeats have been changed. Updates the remaining xoun

    def repeatValueChanged_CB(self, event=None):
        #
        #   Changing the "repeat" count results in the update of number of scans remaining
        #
        self.remainingCount_VAR.set(self.repeat_VAR.get())

    def select_Repeat_1x_CB(self):
        self.repeat_VAR.set('1')
        self.remainingCount_VAR.set('1')

    def select_Repeat_5x_CB(self):
        self.repeat_VAR.set('5')
        self.remainingCount_VAR.set('5')

    def select_Repeat_10x_CB(self):
        self.repeat_VAR.set('10')
        self.remainingCount_VAR.set('10')

    def select_Repeat_15x_CB(self):
        self.repeat_VAR.set('15')
        self.remainingCount_VAR.set('15')

    def select_Repeat_20x_CB(self):
        self.repeat_VAR.set('20')
        self.remainingCount_VAR.set('20')

    def select_Repeat_50x_CB(self):
        self.repeat_VAR.set('50')
        self.remainingCount_VAR.set('50')


    #
    #   Callback when bandwidth has been changed. Updates the UX Parameters and kicks off a new
    #   scan by using the recenter_CB.
    #


    def updateBandwidth(self, newValue):
        self.bandwidthSelected_VAR.set(newValue)
        self.recenter_CB()

    def select_60k_CB(self):
        self.updateBandwidth(self.bandwidthValues['60k'])

    def select_120k_CB(self):
        self.updateBandwidth(self.bandwidthValues['120k'])

    def select_240k_CB(self):
        self.updateBandwidth(self.bandwidthValues['240k'])

    def select_360k_CB(self):
        self.updateBandwidth(self.bandwidthValues['360k'])

    def select_480k_CB(self):
        self.updateBandwidth(self.bandwidthValues['480k'])


    def recenter_CB(self):
        #
        #   When the recenter button is pressed, the frequency is changed to the button position and the start/end frequencies
        #   are modified to recognize a new center frequency
        #


        self.lastCenterFrequency = self.centerFrequency
        self.centerFrequency = int(gv.unformatFrequency(self.currentFrequency_VAR.get()))
        self.mainWindow.theRadio.Set_New_Frequency(self.centerFrequency)
        self.frequencyTuning_VAR.set(60)
        self.updateScanParameters()

        self.updateTuningLine()
        self.startSpectrum_CB()


    def runSpectrumScan(self):
        #
        #   kicks off a scan by telling the radio to talk to the DSP and ask for data according
        #   to the previously set parameters
        #

        self.reinitializeValues()       # set peak and average values back to zero
        self.plotterAvg.clearCanvas()   # clear the canvases
        self.plotterPeak.clearCanvas()
        self.mainWindow.theRadio.startFrequencySpectrumScan(self.startFrequency, int(self.repeat_VAR.get()))


    def parameterStatus(self, status):
        #
        #   Convenience routine to turn all the buttons on or off. When Start button is called, all these
        #   buttons are "disabled". When the scan is done, they are re-enabled.
        #


        self.bandwidth_Menubutton.configure(state=status)
        self.repeat_Menubutton.configure(state=status)

        self.recenter_Button.configure(state=status)
        self.startStop_Button.configure(state=status)

        self.applyClose_Button.configure(state=status)
        self.cancel_Button.configure(state=status)

        self.frequencyTuning_Scale.configure(state=status)

        if self.spectrumScanning:
            self.startStopSpectrum_VAR.set("Running")
        else:
            self.startStopSpectrum_VAR.set("Scan")




    def startSpectrum_CB(self):
        #
        #   run when start button is pressed
        #   Basically sets the flag that scanning is going on (spectrumScanning)
        #   And sets the UX to disabled to avoid confusion mid execution of the scan
        #

        self.spectrumScanning = True

        self.remainingCount_VAR.set(int(self.repeat_VAR.get()))
        self.parameterStatus("disabled")
        self.runSpectrumScan()


    def scanningComplete(self):
        #
        #   Run after all scanning runs have been completed
        #   Re-enables the UX
        #
        self.spectrumScanning = False
        self.parameterStatus("normal")



    #
    #   resizeCanvas_CB and refreshCanvas work together to deal with any resizing of the canvas.
    #   When a resize is detected, resizeCanvas_CB is called and it schedules a future execution of
    #   refreshCanvas.  But resizing generates a lot of callbacks... So if the resize process is underway
    #   each new event cancels the prior "after refreshCanvas" and creates a new one 100ms in the future
    #   Eventually the events end, and the last refreshCanvas future event runs and replots the data
    #
    def resizeCanvas_CB(self, event=None):
        if self.windowResized:
            self.master.after_cancel(self.windowResizedObj)
        else:
            self.windowResized = True
        self.windowResizedObj = self.master.after(gv.config.get_MCU_Update_Period(), self.refreshCanvas)

    #
    #   Refreshes the canvas if the window has been resized.
    #

    def refreshCanvas(self):
        if self.initUXComplete:
            #
            #   Update canvas size
            #
            self.plotterAvg.refreshCanvas()
            self.plotterPeak.refreshCanvas()
            self.updateTuningLine()

    #
    #   This routine checks to see if the frequency has changed and if so, updates the target lines on the graph. It
    #   then reschedules itself to check again later.
    #   It also does nothing if the user happens to be scrolling while it is checking (frequencyScrolling would be True in that case
    #

    def checkForFrequencyChange(self):
        if (self.mainWindow.theVFO_Object.getIntPrimaryVFO() != int(gv.unformatFrequency(self.currentFrequency_VAR.get()))) and (self.frequencyScrolling == False):
            self.lastCenterFrequency = self.centerFrequency
            self.centerFrequency = self.mainWindow.theVFO_Object.getIntPrimaryVFO()
            self.currentFrequency_VAR.set(gv.formatVFO(str(self.centerFrequency)))
            #
            # Calculate new tuning bar position
            #
            barPos = int((self.centerFrequency - self.startFrequency)/int(self.calculatedSampleSize_VAR.get()))
            self.frequencyTuning_VAR.set(barPos)
            self.updateTuningLine()

        self.frequencyChangeCheckPtr = self.master.after(gv.config.get_MCU_Update_Period(),self.checkForFrequencyChange)



    def applyClose_CB(self):
        #
        #   Needs to invoke a mainWindow routine instead of directly calling these attributes
        #
        self.mainWindow.frequencySpectrumMode = "FreqScan"
        self.mainWindow.consumerDSPdata = self.mainWindow
        self.mainWindow.highlightCWorSpectrumBoxes(True)
        self.mainWindow.theRadio.Set_Spectrum_Mode(95)
        self.mainWindow.theRadio.Set_New_Frequency(self.centerFrequency)
        self.mainWindow.consumerSpectrumdata = None
        if self.frequencyChangeCheckPtr != None:
            self.master.after_cancel(self.frequencyChangeCheckPtr)
        self.destroy()


    def cancel_CB(self):
        #
        # self.originalFrequency = centerFrequency
        # need to reset frequency to original if user cancels
        #

        self.mainWindow.frequencySpectrumMode = "FreqScan"
        self.mainWindow.consumerDSPdata = self.mainWindow
        self.mainWindow.highlightCWorSpectrumBoxes(True)
        self.mainWindow.theRadio.Set_Spectrum_Mode(95)
        self.mainWindow.theRadio.Set_New_Frequency(self.originalFrequency)
        self.mainWindow.consumerSpectrumdata = None
        if self.frequencyChangeCheckPtr != None:
            self.master.after_cancel(self.frequencyChangeCheckPtr)
        self.destroy()


